name: Run Automated Tests

on:  
  push:    
    branches:
      - "**"

concurrency:
  group:  ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write
  packages: write
  issues: write

jobs:
  run-ui-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        browser: [ chrome, firefox ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Perform lint
      run: |
        echo peform lint here
      
    - name: Run UI tests
      run: pytest -m web --browser ${{ matrix.browser }} --junit-xml=test-results.xml

    - name: Publish Test Report
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: UI Test Results - ${{ matrix.browser }}
          files: |
            test-results.xml

  run-api-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Perform lint
      run: |
        echo peform lint here
      
    - name: Run API tests
      run: pytest -m api --junit-xml=test-results.xml
    
    - name: Publish Test Report
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: API Test Results
          files: |
            test-results.xml


